# Site
repository: ChrisGoettfert/ChrisGoettfert.github.io
favicon: images/cg-logo-v1.png

# Content configuration version
version: 2

# Personal info
name: Christopher Göttfert, M.Sc. 
title: XR Developer & AI Enthusiast 
email: Chrisi.Goettfert(at)gmail.com
# email_title: Email (Email title override)
# phone: 
# phone_title: Phone (Phone title override)
#website: Your website (eg. https://google.com)(optional)
# website_title: Web (Website title override)

# Dark Mode (true/false/never)
darkmode: false

# Social links
#twitter_username: jekyllrb
github_username:  ChrisGoettfert
#stackoverflow_username: "00000001"
#dribbble_username: jekyll
#facebook_username: jekyll
#flickr_username: jekyll
#instagram_username: jekyll
linkedin_username: christopher-göttfert-556649160
xing_username: Christopher_Goettfert
#pinterest_username: jekyll
#youtube_username: jekyll
orcid_username: 0000-0002-6959-093X
#googlescholar_username: D847cGsAAAAJ

# Additional icon links
#additional_links:
#- title: Link name
 # icon: Font Awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
 # url: Link url (eg. https://google.com)
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me (Use this to override about section title)
about_profile_image: images/me-cropped.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name is Christopher Göttfert and I'm currently working as an XR Developer at Mercedes-Benz AG. <br>

  I work on Mixed and Virtual Reality Applications for the digital after-sales. <br>
  
  Previously, I completed a Master of Science degree in Human-Computer-Interaction and was working as a Research Assistant at the University of Würzburg.

  The things that I currently have the most experience working with are: 
  <mark>VR/AR/XR</mark>, 
  <mark>Unity Development</mark>, 
  <mark>C#</mark>, 
  <mark>Python</mark> and
  <mark>Real-time Interactive Systems </mark>. 
  



content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        border: weak  
        title: HiAvA
        link: https://www.hci.uni-wuerzburg.de/projects/hiava/
        title_link: Research project @ JMU Würzburg
        quote: >
          HiAvA - Scalable Hybrid Avatar-Agents-Technology for Everyday Social Interaction in XR
        description: | # this will include new lines to allow paragraphs
          HiAvA enables a quality leap for diverse collaborative and communicative XR environments of a future cyberspace and allows everyday participation in social VR applications even with limited hardware equipment. The project will develop and evaluate solutions for non-contact tracking of bodies and faces. HiAvA will enable participation in natural social interactions in XR environments, when using a VR headset, tablet, smartphone, or laptop to participate.
          
          My responsibilities lie in the project organization, development of the platform as well as the impact research of various social XR factors.
      - layout: left
        border: weak  
        title: Mirror Exposure Gaze Analyzer
        title_link: Student project
        additional_links:
          - title:  Github page for project
            icon: fab fa-github
            url: https://github.com/ChrisGoettfert/mirror-exposure-gaze-analyzer
          - title: Project summary presented at the HCI expo 2021
            icon: fab fa-youtube
            url: https://www.youtube.com/watch?v=z6zgy7hokIg 
        quote: >
          Implementation of an automatic framework to analyze eye-tracking data in a mirror exposure. 
        description: | # this will include new lines to allow paragraphs
          Creation of an automated evaluation pipeline in Python to evaluate data of a mirror exposure in a short time. Based on measured body sizes of a test person, areas of interest are automatically generated and fixations on them are measured and visualized. 

          Published at the Mensch und Computer Conference 2022. Read the [Paper](https://dl.acm.org/doi/10.1145/3543758.3547567) here.
      - layout: left
        border: weak  
        title: HoloLens Garage Support
        title_link: Work project at TecAlliance
        additional_links:
          - title: Teaser video of the developed HoloLens application
            icon: fab fa-youtube
            url: https://www.youtube.com/watch?v=gPEBEKCNHH8
        quote: >
          Implementation of an Unity application for the HoloLens2 to support automotive mechanics in workshops. 
        description: | # this will include new lines to allow paragraphs
          Development of an Unity application to support mechanics in a workshop scenario. We used computer vision to recognize parts, text recognition to read out codes, and various interaction options and user interfaces. 
      
      - layout: left
        border: weak  
        title: 3D User Interfaces course project
        subtitle: Student project
        additional_links:
          - title: Teaser video of my application for the 3D User Interfaces course
            icon: fab fa-youtube
            url: https://www.youtube.com/watch?v=wwXwdwRLo9U
        quote: >
          Implementation of an Unity VR for the Oculus Rift S with basic VR interaction modalities such as locomotion, raycast interaction, object interaction, teleportation and more. 
        description: | # this will include new lines to allow paragraphs


  - title: Experience
    layout: list
    content:
      -  layout: left
         title: Mercedes-Benz, <br> Stuttgart
         sub_title: XR Developer
         caption: August 2023 - present
         link: https://www.mercedes-benz.de/passengercars.html?subgroup=see-all&group=all&view=BODYTYPE
         quote: >
          XR Developer for the digital after-sales.
         description: | # this will include new lines to allow paragraphs
          Developing XR applications for the digital after-sales. Additionally, I serve as the product owner for a rolled-out mixed-reality application designed to enhance the repair process by providing MR visualizations that support the technician.
      - layout: left
        title: University of Würzburg, <br> Würzburg
        sub_title: Research Assistant
        caption: November 2021 - June 2023
        link: https://www.hci.uni-wuerzburg.de/
        quote: >
          Research Assistant at the HCI Chair at the University of Würzburg.
        description: | # this will include new lines to allow paragraphs
          Working in the [HiAvA](https://www.hci.uni-wuerzburg.de/projects/hiava/) project and focusing on the development of the system platform for different end devices (VR-HMDs, iPhones and Desktops) as well as integration work of features of the other project partners and research about different locomotion techniques and their effect on other participants within a social XR.
      - layout: left
        title: TecAlliance, <br> Würzburg
        sub_title: Working student
        caption: March 2020 - October 2021
        link: https://www.tecalliance.net/de/
        quote: >
          Working student in the Research & Innovation Team at TecAlliance. 
        description: | # this will include new lines to allow paragraphs
          HoloLens2 development & machine learning e.g. different [YOLO](https://arxiv.org/abs/1506.02640) architectures and image recognition via [Google cloud vision](https://cloud.google.com/vision?hl=en) and [Microsoft custom vision](https://www.customvision.ai/) 
      - layout: left
        title: Audi, <br> Ingolstadt
        sub_title: Internship
        caption: April 2019 - September 2019
        link: https://www.audi.de/de/brand/de.html
        quote: >
          Internship at Audi Production Lab as a software developer in virtual/augmented reality. 
        description: | # this will include new lines to allow paragraphs
         Collaboration in the project: [Virtual 3P Workshops in Virtual Reality](https://automanager.tv/?p=13349). Creation of an automated python based data conversion pipeline for CAD data to be used in virtual reality applications. <br> 
         Admission to the Audi Talent Program for students.
      - layout: left
        title: Unversity of Würzburg, <br> Würzburg
        sub_title: Working Student
        caption: August 2018 - March 2019
        link: https://www.hci.uni-wuerzburg.de/
        quote: >
          Student assistant at the HCI Chair of the University of Würzburg. 
        description: | # this will include new lines to allow paragraphs
         Software development in virtual reality using Unity and conducting subject studies in VR. Collaboration in the projects: [Illusion of Virtual Body Ownership](https://www.hci.uni-wuerzburg.de/projects/ivbo/) and [InjectX - Augmenting Social Behavior](https://www.hci.uni-wuerzburg.de/projects/injectx/)
  - title: Education
    layout: list
    content:
      - layout: left
        title: University of Würzburg
        sub_title: Master of Science
        caption: 2019 - 2022
        quote: >
          Master of Science in Human-Computer-Interaction.
        description: | # this will include new lines to allow paragraphs
           Principles of real-time interactive systems, Psychology of real-time interactive systems, Machine Learning, Theorys of HCI, Eye-tracking, Advanced methods of data analysis, Networking and Concurrent Programming, 3D User-interfaces, Multimodal Interactions. <br>
           
           Master Thesis: Stress Generation and Social Ostracism with Teenagers in Virtual Reality - Implementation and Evaluation of an Interactive Therapeutic VR Application supervised by Prof. Dr. Carolin Wienrich and Prof. Dr. Marc Erich Latoschik. - *currently under assessment* <br>
           
           Grade: *Preliminary*: 1.3
      - layout: left
        title: University of Würzburg
        sub_title: Bachelor of Science
        caption: 2015 - 2019
        quote: >
          Bachelor of Science in Human-Computer-Systems.
        description: | # this will include new lines to allow paragraphs
           Introduction to Programming, Algorithms and Data structures, Interactive Computergraphic, Introduction to Human-Computer-Interaction, Research Methods, Statistics, Augmented Reality and User Research. <br> 
           
           Bachelor Thesis: Influence of cognitive load on Simulator sickness in a simulated autonomous driving supervised by Prof. Dr. Carolin Wienrich. Grade: 1.3 <br>
           
           Grade: 2.2        
  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      During my free time I like to do sports, like soccer or strength training. I also enjoy a cold beer while having interesting and insightful conversations. 


# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]
